################################################################################
# aws_prometheus_alert_manager_definition - Amazon Managed Service for Prometheus Alert Manager Definition
################################################################################
# Provider Version: 6.28.0
# Resource Type: aws_prometheus_alert_manager_definition
# Official Documentation: https://raw.githubusercontent.com/hashicorp/terraform-provider-aws/main/website/docs/r/prometheus_alert_manager_definition.html.markdown
#
# Description:
# Manages an Amazon Managed Service for Prometheus (AMP) Alert Manager Definition.
# Alert Manager processes alerts generated by Prometheus alerting rules, handling
# deduplication, grouping, and routing to downstream receivers.
#
# Use Cases:
# - Route Prometheus alerts to Amazon SNS topics
# - Manage alert deduplication and grouping
# - Configure alert inhibition rules
# - Set up silences for maintenance windows
# - Customize alert message templates
#
# Key Features:
# - Alert deduplication and grouping
# - Routing alerts based on labels
# - Inhibition rules to suppress related alerts
# - Silence functionality for maintenance periods
# - Amazon SNS integration (only supported receiver)
# - Prometheus template support for custom messages
################################################################################

resource "aws_prometheus_alert_manager_definition" "example" {
  ################################################################################
  # Basic Configuration
  ################################################################################

  # workspace_id - (Required)
  # Description: ID of the prometheus workspace the alert manager definition should be linked to
  # Type: string
  # Note: References the workspace where alerting rules are defined
  # Example: "ws-12345678-1234-1234-1234-123456789012"
  # See more: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-create-workspace.html
  workspace_id = aws_prometheus_workspace.example.id

  # definition - (Required)
  # Description: The alert manager definition that you want to be applied (YAML format)
  # Type: string
  # Note: Must contain all configuration inside alertmanager_config key
  # Only Amazon SNS is supported as receiver
  # See more: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alert-manager.html
  #
  # Structure:
  # alertmanager_config: |
  #   route:
  #     receiver: 'receiver-name'
  #     [optional routing configuration]
  #   receivers:
  #     - name: 'receiver-name'
  #       sns_configs:
  #         - topic_arn: arn:aws:sns:region:account:topic
  #           sigv4:
  #             region: region
  #
  # Optional sections:
  # - template_files: Prometheus templates for custom message formatting
  # - inhibit_rules: Rules to suppress certain alerts
  # - global: Global configuration settings
  definition = <<EOF
alertmanager_config: |
  route:
    receiver: 'default'
  receivers:
    - name: 'default'
EOF

  ################################################################################
  # Region Configuration
  ################################################################################

  # region - (Optional)
  # Description: Region where this resource will be managed
  # Type: string
  # Default: Defaults to the Region set in the provider configuration
  # Note: This is an advanced configuration option
  # See more: https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
  # Example: "us-east-1", "eu-west-1"
  # region = "us-east-1"
}

################################################################################
# Computed Attributes (Read-Only)
################################################################################
#
# These attributes are exported by the resource and can be referenced:
#
# - id (string)
#   Description: Identifier of the alert manager definition (same as workspace_id)
#   Example: aws_prometheus_alert_manager_definition.example.id
#

################################################################################
# Example Usage Scenarios
################################################################################

# Example 1: Basic Alert Manager with SNS
# resource "aws_prometheus_alert_manager_definition" "basic_sns" {
#   workspace_id = aws_prometheus_workspace.example.id
#
#   definition = <<EOF
# alertmanager_config: |
#   route:
#     receiver: 'default'
#     group_by: ['alertname', 'cluster', 'service']
#     group_wait: 30s
#     group_interval: 5m
#     repeat_interval: 4h
#
#   receivers:
#     - name: 'default'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:123456789012:prometheus-alerts
#         sigv4:
#           region: us-east-1
#         attributes:
#           key: severity
#           value: critical
# EOF
# }

# Example 2: Multiple Receivers with Routing Rules
# resource "aws_prometheus_alert_manager_definition" "multi_receiver" {
#   workspace_id = aws_prometheus_workspace.example.id
#
#   definition = <<EOF
# alertmanager_config: |
#   route:
#     receiver: 'default'
#     group_by: ['alertname', 'cluster']
#     group_wait: 30s
#     group_interval: 5m
#     repeat_interval: 12h
#
#     routes:
#       - match:
#           severity: critical
#         receiver: critical-alerts
#         repeat_interval: 1h
#
#       - match:
#           team: platform
#         receiver: team-platform
#         repeat_interval: 4h
#
#   receivers:
#     - name: 'default'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:123456789012:alerts-default
#         sigv4:
#           region: us-east-1
#
#     - name: 'critical-alerts'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:123456789012:alerts-critical
#         sigv4:
#           region: us-east-1
#         attributes:
#           key: severity
#           value: critical
#
#     - name: 'team-platform'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:123456789012:alerts-platform
#         sigv4:
#           region: us-east-1
#         attributes:
#           key: team
#           value: platform
# EOF
# }

# Example 3: Custom Message Templates
# resource "aws_prometheus_alert_manager_definition" "with_templates" {
#   workspace_id = aws_prometheus_workspace.example.id
#
#   definition = <<EOF
# template_files:
#   custom_template: |
#     {{ define "sns.default.subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Alert{{ end }}
#
#     {{ define "sns.default.message" }}
#     Environment: Production
#     Status: {{ .Status }}
#
#     {{ if gt (len .Alerts.Firing) 0 -}}
#     Firing Alerts:
#     {{ range .Alerts.Firing -}}
#     - Alert: {{ .Labels.alertname }}
#       Severity: {{ .Labels.severity }}
#       Summary: {{ .Annotations.summary }}
#       Description: {{ .Annotations.description }}
#     {{ end }}
#     {{- end }}
#
#     {{ if gt (len .Alerts.Resolved) 0 -}}
#     Resolved Alerts:
#     {{ range .Alerts.Resolved -}}
#     - Alert: {{ .Labels.alertname }}
#       Resolved at: {{ .StartsAt }}
#     {{ end }}
#     {{- end }}
#     {{ end }}
#
# alertmanager_config: |
#   global:
#   templates:
#     - 'custom_template'
#
#   route:
#     receiver: default
#     group_by: ['alertname', 'severity']
#     group_wait: 30s
#     group_interval: 5m
#     repeat_interval: 4h
#
#   receivers:
#     - name: 'default'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:123456789012:prometheus-alerts
#         sigv4:
#           region: us-east-1
#         subject: '{{ template "sns.default.subject" . }}'
#         message: '{{ template "sns.default.message" . }}'
# EOF
# }

# Example 4: Inhibition Rules
# resource "aws_prometheus_alert_manager_definition" "with_inhibition" {
#   workspace_id = aws_prometheus_workspace.example.id
#
#   definition = <<EOF
# alertmanager_config: |
#   route:
#     receiver: 'default'
#     group_by: ['alertname', 'cluster']
#
#   inhibit_rules:
#     # If node is down, suppress service alerts on that node
#     - source_match:
#         severity: critical
#         alertname: NodeDown
#       target_match:
#         severity: warning
#       equal: ['node']
#
#     # If database is down, suppress connection errors
#     - source_match:
#         alertname: DatabaseDown
#       target_match:
#         alertname: DatabaseConnectionError
#       equal: ['cluster']
#
#   receivers:
#     - name: 'default'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:123456789012:prometheus-alerts
#         sigv4:
#           region: us-east-1
# EOF
# }

# Example 5: Complete Configuration with All Features
# resource "aws_prometheus_alert_manager_definition" "complete" {
#   workspace_id = aws_prometheus_workspace.example.id
#   region       = "us-east-1"
#
#   definition = <<EOF
# template_files:
#   default_template: |
#     {{ define "sns.default.subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]{{ end }}
#     {{ define "__alertmanager" }}AlertManager{{ end }}
#     {{ define "__alertmanagerURL" }}{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver | urlquery }}{{ end }}
#
# alertmanager_config: |
#   global:
#   templates:
#     - 'default_template'
#
#   route:
#     receiver: default
#     group_by: ['alertname', 'cluster', 'service']
#     group_wait: 10s
#     group_interval: 10s
#     repeat_interval: 1h
#
#     routes:
#       - match:
#           severity: critical
#         receiver: critical-receiver
#         repeat_interval: 30m
#         continue: true
#
#       - match_re:
#           service: ^(foo1|foo2|baz)$
#         receiver: team-X-receiver
#         group_by: [alertname, datacenter, app]
#
#   inhibit_rules:
#     - source_match:
#         severity: 'critical'
#       target_match:
#         severity: 'warning'
#       equal: ['alertname', 'cluster', 'service']
#
#   receivers:
#     - name: 'default'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:accountid:My-Topic
#         sigv4:
#           region: us-east-1
#         attributes:
#           key: severity
#           value: SEV2
#
#     - name: 'critical-receiver'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:accountid:Critical-Topic
#         sigv4:
#           region: us-east-1
#         attributes:
#           key: severity
#           value: SEV1
#
#     - name: 'team-X-receiver'
#       sns_configs:
#       - topic_arn: arn:aws:sns:us-east-1:accountid:TeamX-Topic
#         sigv4:
#           region: us-east-1
#         attributes:
#           key: team
#           value: team-x
# EOF
# }

################################################################################
# Related Resources
################################################################################

# Prometheus Workspace
# resource "aws_prometheus_workspace" "example" {
#   alias = "example-workspace"
#
#   tags = {
#     Name        = "example-prometheus"
#     Environment = "production"
#   }
# }

# SNS Topic for Alerts
# resource "aws_sns_topic" "prometheus_alerts" {
#   name = "prometheus-alerts"
#
#   tags = {
#     Name      = "prometheus-alerts"
#     ManagedBy = "terraform"
#   }
# }

# SNS Topic Policy to Allow Alert Manager to Publish
# resource "aws_sns_topic_policy" "prometheus_alerts" {
#   arn = aws_sns_topic.prometheus_alerts.arn
#
#   policy = jsonencode({
#     Version = "2012-10-17"
#     Statement = [
#       {
#         Effect = "Allow"
#         Principal = {
#           Service = "aps.amazonaws.com"
#         }
#         Action = "SNS:Publish"
#         Resource = aws_sns_topic.prometheus_alerts.arn
#         Condition = {
#           StringEquals = {
#             "aws:SourceAccount" = data.aws_caller_identity.current.account_id
#           }
#         }
#       }
#     ]
#   })
# }

# data "aws_caller_identity" "current" {}

# SNS Topic Subscription (Email)
# resource "aws_sns_topic_subscription" "email_alerts" {
#   topic_arn = aws_sns_topic.prometheus_alerts.arn
#   protocol  = "email"
#   endpoint  = "alerts@example.com"
# }

################################################################################
# Alert Manager Configuration Reference
################################################################################
#
# Route Configuration:
# - receiver: Default receiver name (required)
# - group_by: List of labels to group alerts by
# - group_wait: Time to wait before sending initial notification (default: 30s)
# - group_interval: Time to wait before sending updated notification (default: 5m)
# - repeat_interval: Time to wait before re-sending notification (default: 4h, max: 5 days)
# - continue: Whether to continue matching subsequent routes (default: false)
# - match: Equality matchers (key-value pairs)
# - match_re: Regex matchers (key-regex pairs)
# - routes: Child routes for conditional routing
#
# Receiver Configuration (SNS):
# - name: Receiver name (required)
# - sns_configs: List of SNS configurations
#   - topic_arn: ARN of the SNS topic (required)
#   - sigv4: SigV4 authentication (required)
#     - region: AWS region (required)
#   - subject: Custom subject template (optional)
#   - message: Custom message template (optional)
#   - attributes: Custom SNS message attributes (optional)
#     - key: Attribute name
#     - value: Attribute value
#
# Inhibition Rules:
# - source_match: Labels that must match in source alerts
# - source_match_re: Regex labels that must match in source alerts
# - target_match: Labels that must match in target alerts
# - target_match_re: Regex labels that must match in target alerts
# - equal: Labels that must have equal values in source and target
#
# Template Files:
# - Use Prometheus template language (Go templates)
# - Define custom subjects and messages
# - Access alert data via template variables
# - Reference: https://prometheus.io/docs/prometheus/latest/configuration/template_reference/

################################################################################
# Important Notes and Best Practices
################################################################################
#
# 1. Configuration Format:
#    - Must use YAML format with alertmanager_config root key
#    - Template files are optional but powerful for customization
#    - Indentation is critical in YAML - use consistent spacing
#
# 2. Receiver Limitations:
#    - Only Amazon SNS is currently supported
#    - Other receiver types (email, webhook, etc.) will cause rejection
#    - SNS topic must be in the same region as the workspace
#
# 3. Repeat Interval Constraint:
#    - Maximum repeat_interval is 5 days
#    - Values exceeding 5 days are automatically capped
#    - Consider alert fatigue when setting intervals
#
# 4. IAM Permissions:
#    - Alert Manager needs permission to publish to SNS topics
#    - Use SNS topic policy to grant aps.amazonaws.com access
#    - Include SourceAccount condition for security
#
# 5. Region Consistency:
#    - SNS sigv4 region must match SNS topic ARN region
#    - Cross-region SNS publishing is not supported
#    - Ensure workspace and SNS topics are in the same region
#
# 6. Grouping Strategy:
#    - Group related alerts to reduce notification noise
#    - Common grouping: ['alertname', 'cluster', 'service']
#    - Balance between context and notification volume
#
# 7. Routing Best Practices:
#    - Define specific routes before catch-all routes
#    - Use severity labels for prioritization
#    - Consider team-based routing for organizational efficiency
#    - Test routing rules thoroughly before production
#
# 8. Inhibition Rules:
#    - Use to suppress redundant alerts
#    - Example: Suppress service alerts when node is down
#    - Define clear source and target relationships
#    - Test inhibition logic in non-production first
#
# 9. Template Customization:
#    - Use templates to format messages for clarity
#    - Include relevant context (severity, description, etc.)
#    - Test templates with sample alert data
#    - Reference Prometheus template documentation
#
# 10. Monitoring and Troubleshooting:
#     - Enable CloudWatch Logs for Alert Manager
#     - Monitor CloudWatch metrics:
#       - SecretFetchFailure
#       - AlertManagerNotificationsThrottledByIntegration
#       - AlertManagerNotificationsFailedByIntegration
#     - Check SNS topic delivery status
#     - Verify SNS topic policies and subscriptions
#
# 11. Configuration Updates:
#     - Changes apply immediately without downtime
#     - Validate YAML syntax before applying
#     - Test in development environment first
#     - Keep backup of working configurations
#
# 12. SNS Topic Design:
#     - Separate topics for different severity levels
#     - Team-specific topics for better ownership
#     - Configure appropriate SNS subscriptions (email, Lambda, etc.)
#     - Set up dead-letter queues for failed deliveries
#
# 13. Silence Management:
#     - Silences are configured via Prometheus API, not Terraform
#     - Use for planned maintenance windows
#     - Document silence procedures in runbooks
#
# 14. Testing Strategy:
#     - Create test alerts to verify routing
#     - Validate SNS topic delivery
#     - Test inhibition rules behavior
#     - Verify template rendering
#
# 15. Cost Considerations:
#     - SNS publishes incur charges per message
#     - Group alerts to reduce SNS API calls
#     - Set appropriate repeat intervals
#     - Monitor SNS usage in Cost Explorer

################################################################################
# Additional Resources
################################################################################
#
# AWS Documentation:
# - Alert Manager Guide: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alert-manager.html
# - Alert Manager Config: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alertmanager-config.html
# - Alert Manager Receiver: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alertmanager-receiver.html
# - API Reference: https://docs.aws.amazon.com/prometheus/latest/APIReference/yaml-AlertManagerDefinitionData.html
#
# Terraform Documentation:
# - Resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/prometheus_alert_manager_definition
#
# Prometheus Documentation:
# - Alertmanager Configuration: https://prometheus.io/docs/alerting/latest/configuration/
# - Template Reference: https://prometheus.io/docs/prometheus/latest/configuration/template_reference/
# - Template Examples: https://prometheus.io/docs/prometheus/latest/configuration/template_examples/
#
# Related AWS Services:
# - Amazon SNS: For alert notifications
# - Amazon Managed Grafana: For alert visualization
# - AWS CloudWatch: For Alert Manager logs and metrics
# - AWS Secrets Manager: For PagerDuty integration keys
#
