################################################################################
# Terraform AWS Provider Resource Template
# Resource: aws_datasync_location_azure_blob
#
# Generated: 2026-01-19
# Provider Version: 6.28.0
#
# Note: This template is generated based on the provider version at the time of
# generation. For the latest specifications, please refer to the official
# Terraform AWS Provider documentation.
#
# Official Documentation:
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_location_azure_blob
#
# AWS Service Documentation:
# https://docs.aws.amazon.com/datasync/latest/userguide/creating-azure-blob-location.html
################################################################################

resource "aws_datasync_location_azure_blob" "example" {
  ##############################################################################
  # Required Arguments
  ##############################################################################

  # agent_arns - (Required) A list of DataSync Agent ARNs with which this
  # location will be associated. The DataSync Agents must be available before
  # creating this resource. DataSync agents enable transfers between Azure Blob
  # Storage and AWS storage services. Agents are required for transfers to/from
  # Amazon EFS or Amazon FSx, or when using Basic mode tasks. Transfers between
  # Azure Blob and Amazon S3 using Enhanced mode do not require agents.
  # Type: set(string)
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  agent_arns = ["arn:aws:datasync:us-east-1:123456789012:agent/agent-0123456789abcdef0"]

  # authentication_type - (Required) The authentication method DataSync uses to
  # access your Azure Blob Storage. Currently, only SAS (Shared Access Signature)
  # authentication is supported. SAS tokens provide secure delegated access to
  # resources in your storage account. The token must have appropriate permissions
  # based on the transfer direction (read for source, write for destination).
  # Type: string
  # Valid values: SAS
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  authentication_type = "SAS"

  # container_url - (Required) The URL of the Azure Blob Storage container
  # involved in your transfer. This URL points to the specific container where
  # DataSync will read from or write to. The URL format is typically:
  # https://{storage-account-name}.blob.core.windows.net/{container-name}
  # Type: string
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  container_url = "https://myaccount.blob.core.windows.net/mycontainer"

  ##############################################################################
  # Optional Arguments
  ##############################################################################

  # access_tier - (Optional) The access tier that you want your objects or files
  # transferred into. Azure Blob Storage offers different access tiers to optimize
  # storage costs based on data access patterns:
  # - HOT: For data that is accessed frequently
  # - COOL: For data that is infrequently accessed and stored for at least 30 days
  # - ARCHIVE: For data that is rarely accessed and stored for at least 180 days
  # Note: DataSync can copy objects into the archive tier but cannot verify the
  # transfer if trying to verify all data in the destination when copying objects
  # into the archive access tier. When transferring FROM Azure Blob Storage,
  # DataSync can copy objects in hot and cool tiers, but objects in the archive
  # tier must be rehydrated first.
  # Type: string
  # Valid values: HOT, COOL, ARCHIVE
  # Default: HOT
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  access_tier = "HOT"

  # blob_type - (Optional) The type of blob that you want your objects or files
  # to be when transferring them into Azure Blob Storage. Currently, only BLOB
  # (Block Blob) type is supported. Block blobs are optimized for uploading large
  # amounts of data efficiently and are the most common blob type for general-purpose
  # file storage.
  # Type: string
  # Valid values: BLOB
  # Default: BLOB
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  blob_type = "BLOB"

  # id - (Optional) The ID of the DataSync Location. This attribute is both optional
  # and computed. If not specified, it will be automatically generated by AWS.
  # Type: string
  id = null

  # region - (Optional) Region where this resource will be managed. This allows you
  # to specify a different region than the one set in the provider configuration.
  # Defaults to the Region set in the provider configuration if not specified.
  # Type: string
  # AWS API Reference: https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
  region = "us-east-1"

  # subdirectory - (Optional) Path segments if you want to limit your transfer to
  # a virtual directory in the container. This allows you to scope the transfer to
  # a specific folder within the Azure Blob Storage container rather than the entire
  # container. The path should not include a leading slash. For example, to transfer
  # only files in a "data/2023" folder, specify "data/2023".
  # Type: string
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  subdirectory = "path/to/directory"

  # tags - (Optional) Key-value pairs of resource tags to assign to the DataSync
  # Location. Tags help you categorize, filter, and search for AWS resources. If
  # configured with a provider default_tags configuration block, tags with matching
  # keys will overwrite those defined at the provider-level.
  # Type: map(string)
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  tags = {
    Name        = "example-azure-blob-location"
    Environment = "production"
  }

  # tags_all - (Optional) A map of tags assigned to the resource, including those
  # inherited from the provider default_tags configuration block. This attribute
  # is both optional and computed.
  # Type: map(string)
  tags_all = {
    Name        = "example-azure-blob-location"
    Environment = "production"
  }

  ##############################################################################
  # Nested Blocks
  ##############################################################################

  # sas_configuration - (Optional) The SAS (Shared Access Signature) configuration
  # that allows DataSync to access your Azure Blob Storage. This block is required
  # when authentication_type is set to "SAS". SAS tokens provide secure, time-limited
  # access to Azure storage resources. The token must grant appropriate permissions:
  # - For source locations: read and list permissions
  # - For destination locations: write, read, list, and delete permissions
  # Note: If the SAS token expires during a transfer, DataSync will no longer be
  # able to access the Azure Blob Storage location, resulting in a "Failed to open
  # directory" error.
  # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationAzureBlob.html
  sas_configuration {
    # token - (Required) A SAS token that provides permissions to access your Azure
    # Blob Storage. The token is a query string that includes authentication and
    # authorization information. SAS tokens can be created at the account level or
    # container level, with container-level tokens recommended for better security
    # isolation. The token must be valid for the entire duration of the transfer.
    # Type: string (sensitive)
    # AWS API Reference: https://docs.aws.amazon.com/datasync/latest/userguide/API_AzureBlobSasConfiguration.html
    token = "sp=r&st=2023-12-20T14:54:52Z&se=2023-12-20T22:54:52Z&spr=https&sv=2021-06-08&sr=c&sig=aBBKDWQvyuVcTPH9EBp%2FXTI9E%2F%2Fmq171%2BZU178wcwqU%3D"
  }

  ##############################################################################
  # Computed Attributes (Read-Only)
  ##############################################################################

  # The following attributes are computed by AWS and cannot be set directly:
  #
  # arn - Amazon Resource Name (ARN) of the DataSync Location
  # Type: string
  #
  # uri - The URI of the Azure Blob Storage location
  # Type: string
  ##############################################################################
}
