################################################################################
# aws_ec2_transit_gateway_route_table - EC2 Transit Gateway Route Table
################################################################################
# Generated: 2026-01-22
# Provider Version: 6.28.0
#
# Note: This template is generated based on the AWS Provider schema at the time
# of creation. For the latest specifications, please refer to the official
# documentation:
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_route_table
#
# AWS Official Documentation:
# https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html
################################################################################

resource "aws_ec2_transit_gateway_route_table" "example" {
  # ============================================================================
  # Required Arguments
  # ============================================================================

  # transit_gateway_id - (Required) Identifier of EC2 Transit Gateway.
  # The Transit Gateway to which this route table will be attached.
  # Type: string
  # AWS API Reference: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayRouteTable.html
  transit_gateway_id = "tgw-1234567890abcdef0"

  # ============================================================================
  # Optional Arguments
  # ============================================================================

  # region - (Optional) Region where this resource will be managed.
  # Defaults to the Region set in the provider configuration.
  # This parameter allows you to specify a different region than the provider default.
  # Type: string
  # Reference: https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
  # region = "us-east-1"

  # tags - (Optional) Key-value tags for the EC2 Transit Gateway Route Table.
  # If configured with a provider default_tags configuration block, tags with
  # matching keys will overwrite those defined at the provider-level.
  # Type: map of strings
  # Reference: https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html
  tags = {
    Name        = "example-tgw-route-table"
    Environment = "production"
    ManagedBy   = "terraform"
  }

  # tags_all - (Optional) A map of tags assigned to the resource, including those
  # inherited from the provider default_tags configuration block.
  # This is typically managed automatically by Terraform when using default_tags.
  # Type: map of strings
  # Note: Generally not set directly; use 'tags' instead and configure default_tags
  # at the provider level if needed.
  # tags_all = {}

  # id - (Optional) EC2 Transit Gateway Route Table identifier.
  # This is typically computed by AWS and should not be set manually in most cases.
  # Type: string
  # Note: This is primarily used for import scenarios. In normal resource creation,
  # this value is automatically generated by AWS.
  # id = "tgw-rtb-1234567890abcdef0"

  # ============================================================================
  # Computed Attributes (Read-Only)
  # ============================================================================
  # The following attributes are computed by AWS and cannot be set in configuration:
  #
  # - arn (string)
  #   EC2 Transit Gateway Route Table Amazon Resource Name (ARN).
  #   Example: "arn:aws:ec2:us-east-1:123456789012:transit-gateway-route-table/tgw-rtb-1234567890abcdef0"
  #
  # - default_association_route_table (bool)
  #   Boolean whether this is the default association route table for the EC2 Transit Gateway.
  #   When attachments are associated with the transit gateway, they use this route table by default
  #   if no other route table is specified.
  #
  # - default_propagation_route_table (bool)
  #   Boolean whether this is the default propagation route table for the EC2 Transit Gateway.
  #   Routes from attachments are automatically propagated to this route table if enabled.
  #
  # These values can be referenced in other resources using:
  # - aws_ec2_transit_gateway_route_table.example.arn
  # - aws_ec2_transit_gateway_route_table.example.default_association_route_table
  # - aws_ec2_transit_gateway_route_table.example.default_propagation_route_table
  # - aws_ec2_transit_gateway_route_table.example.id
}

################################################################################
# Additional Information
################################################################################
#
# Transit Gateway Route Tables:
# Transit gateway route tables are used to configure routing for transit gateway
# attachments. These tables contain rules that determine how network traffic is
# routed between VPCs, VPNs, and other attachments.
#
# Key Concepts:
# - Association: When an attachment is associated with a route table, traffic from
#   that attachment uses the routes in the associated route table.
# - Propagation: When route propagation is enabled, routes from the attachment
#   are automatically added to the route table.
# - Static Routes: You can create static routes in addition to propagated routes.
#
# Common Use Cases:
# 1. Isolated Routing: Create separate route tables for different environments
# 2. Hub-and-Spoke: Use multiple route tables to control traffic flow
# 3. Segmentation: Separate production and non-production traffic
#
# Related Resources:
# - aws_ec2_transit_gateway: Create the transit gateway
# - aws_ec2_transit_gateway_route: Add static routes to the route table
# - aws_ec2_transit_gateway_route_table_association: Associate VPC attachments
# - aws_ec2_transit_gateway_route_table_propagation: Enable route propagation
#
# AWS Documentation:
# - Transit Gateway Route Tables: https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html
# - Create Route Table: https://docs.aws.amazon.com/vpc/latest/tgw/create-tgw-route-table.html
# - API Reference: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayRouteTable.html
#
################################################################################
