################################################################################
# AWS Signer Signing Profile Permission
# Resource: aws_signer_signing_profile_permission
# Provider Version: 6.28.0
#
# Description:
# Creates a Signer Signing Profile Permission. That is, a cross-account
# permission for a signing profile.
#
# Use Cases:
# - Grant cross-account access to signing profiles
# - Allow other AWS accounts to start signing jobs
# - Enable signature revocation from other accounts
# - Provide read access to signing profiles
################################################################################

resource "aws_signer_signing_profile_permission" "example" {
  #-----------------------------------------------------------------------------
  # REQUIRED PARAMETERS
  # These parameters must be configured for the resource to work properly
  #-----------------------------------------------------------------------------

  # profile_name - (Required)
  # Name of the signing profile to add the cross-account permissions.
  #
  # Type: string
  # Example: "my-signing-profile"
  # Reference: aws_signer_signing_profile.prod_sp.name
  profile_name = "REPLACE_WITH_PROFILE_NAME"

  # action - (Required)
  # An AWS Signer action permitted as part of cross-account permissions.
  #
  # Type: string
  # Valid values:
  #   - "signer:StartSigningJob"   - Allow starting signing jobs
  #   - "signer:GetSigningProfile" - Allow reading signing profile details
  #   - "signer:RevokeSignature"   - Allow revoking signatures
  #   - "signer:SignPayload"       - Allow signing payloads
  #
  # Example: "signer:StartSigningJob"
  action = "signer:StartSigningJob"

  # principal - (Required)
  # The AWS principal to be granted a cross-account permission.
  #
  # Type: string
  # Format: Can be an AWS account ID, IAM role ARN, or IAM user ARN
  #
  # Examples:
  #   - "123456789012"                                    (AWS Account ID)
  #   - "arn:aws:iam::123456789012:role/MyRole"         (IAM Role ARN)
  #   - "arn:aws:iam::123456789012:user/MyUser"         (IAM User ARN)
  principal = "REPLACE_WITH_PRINCIPAL"

  #-----------------------------------------------------------------------------
  # OPTIONAL PARAMETERS
  # These parameters have sensible defaults or are optional
  #-----------------------------------------------------------------------------

  # profile_version - (Optional, Computed)
  # The signing profile version that a permission applies to.
  # If not specified, the permission applies to all versions.
  #
  # Type: string
  # Default: Applies to all versions if not specified
  # Computed: Yes - AWS generates a version if not specified
  #
  # Example: "a1b2c3d4"
  # Reference: aws_signer_signing_profile.prod_sp.version
  # profile_version = "REPLACE_WITH_VERSION"

  # statement_id - (Optional, Computed)
  # A unique statement identifier.
  # If not specified, Terraform will generate one automatically.
  # Conflicts with: statement_id_prefix
  #
  # Type: string
  # Default: Auto-generated by Terraform
  # Computed: Yes
  #
  # Example: "ProdAccountStartSigningJob"
  # Note: Must be unique within the signing profile
  # statement_id = "REPLACE_WITH_STATEMENT_ID"

  # statement_id_prefix - (Optional, Computed)
  # A statement identifier prefix. Terraform will generate a unique suffix.
  # Use this when you want a consistent prefix but need uniqueness.
  # Conflicts with: statement_id
  #
  # Type: string
  # Default: None
  # Computed: Yes - Terraform adds a unique suffix
  #
  # Example: "version-permission-" results in "version-permission-20231201123456"
  # Note: Cannot be used with statement_id
  # statement_id_prefix = "REPLACE_WITH_PREFIX"

  # region - (Optional, Computed)
  # Region where this resource will be managed.
  #
  # Type: string
  # Default: Uses the region from provider configuration
  # Computed: Yes
  #
  # Example: "us-east-1"
  # Documentation: https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
  # region = "us-east-1"

  #-----------------------------------------------------------------------------
  # COMPUTED ATTRIBUTES (Read-Only)
  # These attributes are set by AWS and cannot be configured
  #-----------------------------------------------------------------------------

  # id - (Computed)
  # The unique identifier of the signing profile permission.
  # Format: profile_name/statement_id
  #
  # Type: string
  # Usage: Reference as aws_signer_signing_profile_permission.example.id
}

################################################################################
# EXAMPLE CONFIGURATIONS
################################################################################

# Example 1: Basic cross-account permission for starting signing jobs
#
# resource "aws_signer_signing_profile_permission" "basic" {
#   profile_name = aws_signer_signing_profile.prod_sp.name
#   action       = "signer:StartSigningJob"
#   principal    = "123456789012"
# }

# Example 2: Permission with explicit statement ID
#
# resource "aws_signer_signing_profile_permission" "with_statement_id" {
#   profile_name = aws_signer_signing_profile.prod_sp.name
#   action       = "signer:GetSigningProfile"
#   principal    = "arn:aws:iam::123456789012:role/TeamRole"
#   statement_id = "ProdAccountStartSigningJob_StatementId"
# }

# Example 3: Version-specific permission with statement ID prefix
#
# resource "aws_signer_signing_profile_permission" "version_specific" {
#   profile_name        = aws_signer_signing_profile.prod_sp.name
#   action              = "signer:RevokeSignature"
#   principal           = "123456789012"
#   profile_version     = aws_signer_signing_profile.prod_sp.version
#   statement_id_prefix = "version-permission-"
# }

# Example 4: Complete setup with signing profile
#
# resource "aws_signer_signing_profile" "prod_sp" {
#   platform_id = "AWSLambda-SHA384-ECDSA"
#   name_prefix = "prod_sp_"
#
#   signature_validity_period {
#     value = 5
#     type  = "YEARS"
#   }
#
#   tags = {
#     Environment = "production"
#     Team        = "security"
#   }
# }
#
# resource "aws_signer_signing_profile_permission" "lambda_deploy" {
#   profile_name = aws_signer_signing_profile.prod_sp.name
#   action       = "signer:StartSigningJob"
#   principal    = var.deployment_account_id
# }

################################################################################
# COMMON PATTERNS AND BEST PRACTICES
################################################################################

# Best Practices:
#
# 1. Principle of Least Privilege:
#    - Grant only the specific actions needed (StartSigningJob, GetSigningProfile, etc.)
#    - Use specific IAM roles instead of entire AWS accounts when possible
#    - Consider version-specific permissions for tighter control
#
# 2. Statement ID Management:
#    - Use descriptive statement IDs that indicate the purpose
#    - Use statement_id_prefix when creating multiple similar permissions
#    - Avoid statement_id conflicts by using unique identifiers
#
# 3. Cross-Account Access:
#    - Document which accounts have access and why
#    - Regularly audit cross-account permissions
#    - Use IAM role ARNs for more granular control than account IDs
#
# 4. Version Management:
#    - Specify profile_version for version-specific permissions
#    - Omit profile_version to allow access to all versions
#    - Consider the lifecycle of your signing profiles
#
# 5. Security Considerations:
#    - Limit RevokeSignature permission to trusted principals
#    - Monitor SigningJob operations for unusual activity
#    - Use AWS Organizations SCPs for additional guardrails

# Common Use Cases:
#
# 1. Lambda Code Signing:
#    - Grant deployment account StartSigningJob permission
#    - Allow CI/CD pipelines to sign Lambda code
#
# 2. Multi-Account Organizations:
#    - Enable shared signing profiles across accounts
#    - Centralize code signing in a security account
#
# 3. Third-Party Integration:
#    - Grant external vendors GetSigningProfile permission
#    - Allow partners to verify signature validity
#
# 4. Audit and Compliance:
#    - Grant security teams RevokeSignature permission
#    - Enable compliance tools to read signing profiles

# Troubleshooting:
#
# 1. "ConflictException: Statement already exists":
#    - Check for duplicate statement_id values
#    - Use statement_id_prefix for automatic uniqueness
#
# 2. "AccessDeniedException":
#    - Verify the signing profile exists and is accessible
#    - Check IAM permissions for the Terraform execution role
#
# 3. "InvalidParameterException: Invalid action":
#    - Ensure action is one of the four valid values
#    - Check for typos in the action name
#
# 4. Permission not taking effect:
#    - Verify the principal has the necessary IAM permissions
#    - Check for conflicting deny policies in the target account
#    - Ensure the signing profile is in the same region

################################################################################
# REFERENCES
################################################################################

# AWS Signer Documentation:
# - Service Overview: https://docs.aws.amazon.com/signer/
# - Code Signing: https://docs.aws.amazon.com/signer/latest/developerguide/Welcome.html
# - Signing Profiles: https://docs.aws.amazon.com/signer/latest/developerguide/signing-profiles.html
#
# Terraform Documentation:
# - Resource: https://registry.terraform.io/providers/hashicorp/aws/6.28.0/docs/resources/signer_signing_profile_permission
# - Related Resources:
#   - aws_signer_signing_profile: https://registry.terraform.io/providers/hashicorp/aws/6.28.0/docs/resources/signer_signing_profile
#   - aws_signer_signing_job: https://registry.terraform.io/providers/hashicorp/aws/6.28.0/docs/resources/signer_signing_job

################################################################################
# VARIABLES (Example)
################################################################################

# variable "deployment_account_id" {
#   description = "AWS Account ID that needs signing permission"
#   type        = string
# }
#
# variable "team_role_arn" {
#   description = "IAM Role ARN for the team requiring access"
#   type        = string
# }

################################################################################
# OUTPUTS (Example)
################################################################################

# output "permission_id" {
#   description = "The unique identifier of the signing profile permission"
#   value       = aws_signer_signing_profile_permission.example.id
# }
#
# output "permission_statement_id" {
#   description = "The statement ID of the permission"
#   value       = aws_signer_signing_profile_permission.example.statement_id
# }
