################################################################################
# aws_datazone_glossary_term
# Terraform Documentation: https://registry.terraform.io/providers/hashicorp/aws/6.28.0/docs/resources/datazone_glossary_term
# AWS API Documentation: https://docs.aws.amazon.com/datazone/latest/userguide/glossaries.html
# Provider Version: 6.28.0
# Generated: 2026-02-14
# NOTE: このテンプレートは参考例です。環境に応じて適切に値を設定してください。
# Generated by: terraform-aws-annotated-reference
################################################################################

#-------------------------------------------------------------------------------
# リソース定義
#-------------------------------------------------------------------------------
# Amazon DataZone用語集内の用語を管理する
# ビジネス用語の定義、分類、関係性を管理できる
#-------------------------------------------------------------------------------

resource "aws_datazone_glossary_term" "example" {
  #-------
  # 基本設定
  #-------
  # 設定内容: 用語の名前
  # 制約: 用語集内で一意である必要がある
  name = "example-term"

  # 設定内容: この用語が属する用語集の識別子
  # 形式: グローバル一意識別子
  glossary_identifier = "abc123456"

  #-------
  # 説明設定
  #-------
  # 設定内容: 用語の簡潔な説明
  # 用途: 用語の概要を提供する
  # 省略時: 説明なし
  short_description = "A brief description of the term"

  # 設定内容: 用語の詳細な説明
  # 用途: 用語の詳細な定義、使用方法、例などを含む
  # 省略時: 詳細説明なし
  long_description = "A comprehensive description of the term including usage examples and context"

  #-------
  # ドメイン設定
  #-------
  # 設定内容: DataZoneドメインの識別子
  # 省略時: 自動検出
  domain_identifier = "dzd_abc123456"

  #-------
  # リージョン設定
  #-------
  # 設定内容: このリソースを管理するAWSリージョン
  # 省略時: プロバイダー設定のリージョンを使用
  region = "us-east-1"

  #-------
  # ステータス設定
  #-------
  # 設定内容: 用語のステータス
  # 設定可能な値: ENABLED, DISABLED
  # 省略時: ENABLED
  status = "ENABLED"

  #-------
  # 用語関係設定
  #-------
  # 設定内容: この用語と他の用語との関係性
  # 用途: 階層構造や分類を定義する
  # 省略時: 関係性なし
  # term_relations {
  #   # 設定内容: この用語が分類する他の用語の識別子リスト
  #   # 用途: この用語が親カテゴリとして分類する子用語を指定
  #   # 省略時: 分類関係なし
  #   classifies = ["term-id-1", "term-id-2"]
  #
  #   # 設定内容: この用語の親となる用語の識別子リスト
  #   # 用途: この用語が属する上位概念を指定
  #   # 省略時: 上位関係なし
  #   is_a = ["parent-term-id-1"]
  # }

  #-------
  # タイムアウト設定
  #-------
  # 設定内容: リソース作成時のタイムアウト
  # 形式: "30s", "5m", "1h"等の時間文字列
  # 省略時: デフォルトタイムアウトを使用
  # timeouts {
  #   create = "10m"
  # }
}

################################################################################
# 出力例
################################################################################
# このリソースから出力可能な属性値の例
# 実際の使用時は必要に応じてoutputブロックを定義してください

# output "glossary_term_id" {
#   description = "用語の一意識別子"
#   value       = aws_datazone_glossary_term.example.id
# }
#
# output "created_at" {
#   description = "用語の作成日時（RFC3339形式）"
#   value       = aws_datazone_glossary_term.example.created_at
# }
#
# output "created_by" {
#   description = "用語を作成したユーザーの識別子"
#   value       = aws_datazone_glossary_term.example.created_by
# }

################################################################################
# Attributes Reference
################################################################################
# id               - 用語の一意識別子
# created_at       - 用語の作成日時（RFC3339形式）
# created_by       - 用語を作成したユーザーの識別子
